In [1]:
import numpy as np

# Задание 1

# Задание 2

In [95]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

In [80]:
def scalar(a, b):
    res = 0
    for x in range(len(a)):
        res += a[x] * b[x]
    return res 

In [86]:
def matrix_product(a, b):
    if a.shape[1] != b.shape[0]:
        return 'Размеры матриц не совпадают для умножения'
    else:
        result = np.empty([a.shape[0], b.shape[1]])
        for x in range(a.shape[0]):
            for y in range(b.shape[1]):
                result[x][y] = scalar(a[x], b[:,y])
    return result

In [96]:
result_product = matrix_product(a, b)

In [98]:
result_product

array([[  4., -11.],
       [ 12.,  -3.]])

In [99]:
# Проверка корректности через встроенную функцию numpy
print(a.dot(b))

[[  4 -11]
 [ 12  -3]]


In [105]:
def matrix_sum(a, b):
    if a.shape != b.shape:
        return 'Размеры матриц не совпадают для сложения'
    else:
        result = np.empty([a.shape[0], a.shape[1]])
        for x in range(a.shape[0]):
            for y in range(a.shape[1]):
                result[x][y] = a[x][y] + b[x][y]
    return result                

In [106]:
result_sum = matrix_sum(a, b)

In [107]:
result_sum

array([[ 5., -3.],
       [ 3.,  5.]])

In [108]:
# Проверка корректности через встроенную функцию numpy
print(a + b)

[[ 5 -3]
 [ 3  5]]


# Задание 3

In [109]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [119]:
# напишем функцию умножения матрицы на скаляр
def matrix_num_product(a, k):
    result = np.empty([a.shape[0], a.shape[1]])
    for x in range(a.shape[0]):
        for y in range(a.shape[1]):
            result[x][y] = a[x][y] * k
    return result

In [120]:
matrix_num_product(A, 3) - matrix_num_product(B, 2) + matrix_num_product(C, 4)

array([[ 11.,  -5.],
       [  9., -12.]])

In [121]:
# проверим через встроенные функции
print(A*3 - B*2 + C*4)

[[ 11  -5]
 [  9 -12]]


# Задание 4

In [126]:
A = np.array([[4, 1], [5, -2], [2, 3]])

In [127]:
A

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [123]:
# напишем функцию транспонирования
def transponse(a):
    result = np.empty([a.shape[1], a.shape[0]])
    for x in range(a.shape[0]):
        for y in range(a.shape[1]):
            result[y][x] = a[x][y]
    return result

In [128]:
transponse(A)

array([[ 4.,  5.,  2.],
       [ 1., -2.,  3.]])

In [133]:
# проверим результат через встроенную функцию
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [129]:
print(matrix_product(A, transponse(A)))

[[17. 18. 11.]
 [18. 29.  4.]
 [11.  4. 13.]]


In [130]:
print(matrix_product(transponse(A), A))

[[45.  0.]
 [ 0. 14.]]


In [131]:
# проверим на встроенных функциях Numpy
print(A.dot(A.T))

[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [132]:
print(A.T.dot(A))

[[45  0]
 [ 0 14]]


# Задание 5

Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.