In [1]:
import numpy as np

# Задание 1

Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

In [16]:
A = np.array([[-1, -6], [2, 6]])

In [17]:
w1, v1 = np.linalg.eig(A)

In [18]:
print('Собственые числа {}'.format(w1))
print('Собственые вектора {}'.format(v1))

Собственые числа [2. 3.]
Собственые вектора [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


# Задание 2

Дан оператор поворота на 180 градусов, задаваемый матрицей. Показать, что любой вектор является для него собственным.

In [19]:
B = np.array([[-1, 0], [0, -1]])

In [20]:
w2, v2 = np.linalg.eig(B)

In [21]:
w2

array([-1., -1.])

In [22]:
v2

array([[1., 0.],
       [0., 1.]])

In [23]:
print('Система уравнений поиска собственных векторов имеет бесконечное множество решений, значит любой вектор будет собственным {}'.format(v2))

Система уравнений поиска собственных векторов имеет бесконечное множество решений, значит любой вектор будет собственным [[1. 0.]
 [0. 1.]]


# Задание 3

Пусть линейный оператор задан матрицей C. Установить, является ли вектор  𝑥=(1,1)  собственным вектором этого линейного оператора.

In [31]:
C = np.array([[1, 1], [-1, 3]])

In [32]:
w3, v3 = np.linalg.eig(C)

In [33]:
w3

array([2.00000002, 1.99999998])

In [36]:
v3

array([[ 0.70710677, -0.70710679],
       [ 0.70710679, -0.70710677]])

In [39]:
print('Является, так как x1 = x2 {}'.format(v3))

Является, так как x1 = x2 [[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


# Задание 3

Пусть линейный оператор задан матрицей. Установить, является ли вектор  𝑥=(3,−3,−4)  собственным вектором этого линейного оператора.

In [46]:
D = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])

In [47]:
w4, v4 = np.linalg.eig(D)

In [48]:
w4

array([ 3., -3.,  3.])

In [49]:
v4

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [50]:
print('Является, так как условия x3 может быть любым, а x1 = x2 или x1 = -x2, что удовлетворяет условиям')

Является, так как условия x3 может быть любым, а x1 = x2 или x1 = -x2, что удовлетворяет условиям
